#pragma once

void test_bzero();
void test_puts();
void test_isalpha();
void test_isdigit();
void test_isalnum();
void test_strlen();
void test_strcat();
void test_isascii();
void test_memset();
void test_isprint();
void test_memcpy();
void test_strdup();
void test_tolower();
void test_toupper();
void test_cat();
void test_strcpy();
void test_memccpy();
